myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls')),
]
urlpatterns += static(settings.MEDIA_URL,documnet_root=settings.MEDIA_ROOT)

myproject/posts/urls.py
from django.urls import path
from . import views
app_name='posts'
urlpatterns = [
    path('',views.posts_list,name="list"),
    path('<slug:slug>',views.post_page,name="page"),


]

myproject/users/urls.py
from django.urls import path
from . import views
app_name='users'
urlpatterns = [
    path('register/',views.register_view,name="register"),
]

myproject/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title=models.CharField(max_length=75)
    body=models.TextField()
    slug=models.SlugField()
    date=models.DateTimeField(auto_now_add=True)
    banner=models.ImageField(default='fallback.png',blank=True)
    
    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

# Create your models here.

myproject/myproject/views.py
#from django.http import HttpResponse
from django.shortcuts import render
def homepage(request):
    #return HttpResponse("hello world ")
    return render(request,'home.html')

def about(request):
    #return HttpResponse("This is about section")
    return render(request,'about.html')

myproject/posts/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse
def posts_list(request):
    posts=Post.objects.all().order_by('-date')
    return render(request,"posts/posts_list.html",{'posts':posts})

def post_page(request,slug):
    post=Post.objects.get(slug=slug)
    return render(request,"posts/post_page.html",{'post':post})

myproject/users/views.py
from django.shortcuts import render

# Create your views here.
def register_view(request):
    return render(request,"users/register.html")

myproject/posts/templates/posts/post_page.html
{%extends 'layout.html' %}
{%block title%}
{{post.title}}
{%endblock%}
{%block content%}
<section>
    <section >
        <img src="{{post.banner.url}}" 
        alt="{{post.title}}"
        class="banner"
        ></img>
        <h1>{{post.title}} </h1>
        <p>{{post.date}} </p>
        <p>{{post.body}} </p>

    </section>
</section>

<p>check out my <a href="/about">about page </a></p>
{%endblock%}

myproject/posts/templates/posts/posts_list.html
{%extends 'layout.html' %}
{%block title%}
Posts
{%endblock%}
{%block content%}
<section>
    {% for post in posts%}
    <article class="post">
        <h2>
            <a href="{% url 'posts:page' slug=post.slug %} ">
                 {{post.title}}
            </a>
           </h2>
        <p>{{post.date}} </p>
        <p>{{post.body}} </p>
    </article>
    {%endfor%}
</section>

<p>check out my <a href="/about">about page </a></p>
{%endblock%}

myproject/templates/about.html
{%extends 'layout.html' %}
{%block title%}
About
{%endblock%}
{%block content%}
<h1>This is the main page</h1>
    <p>check out my <a href="/">home page </a></p
{%endblock%}

myproject/templates/home.html
{%extends 'layout.html' %}
{%block title%}
home
{%endblock%}
{%block content%}
<h1>This is the main page</h1>
<p>check out my <a href="/about">about page </a></p>
{%endblock%}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {%block title%}
            Django app
        {%endblock %}
    </title>
    <link rel="stylesheet" href="%static 'css/style.css' %">
    <script src="{%static 'js/main.js' %}" defer ></script>
</head>
<body>
    <nav>
        <a href="/">home</a>
        <a href="/about">about</a>
        <a href="{%url 'posts:list' %}">Post</a>

    </nav>
    <main>
        {%block content%}
        {%endblock%}
    </main>
</body>
</html>

myproject/users/templates/users/register.html
{%extends 'layout.html' %}
{%block title%}
Register a new user
{%endblock%}
{%block content%}
<section>
    <h1>Register a user</h1>
</section>
<p>check out my <a href="/about">about page </a></p>
{%endblock%}